builddeb: fix missing headers in linux-headers package on arm architecture
The kernel headers package (linux-headers) doesn't include
the arch/arm/mach-*/include header files.

It makes the package unusable on ARM architecture and prevent
out-of-tree modules build:
 /usr/src/linux-headers-3.14.0/arch/arm/include/asm/memory.h:24:25:
 fatal error: mach/memory.h: No such file or directory
 #include <mach/memory.h>
 ^
 compilation terminated.

While this patch explicitely test arm architecture, avr32 and blackfin are
affected since they ship mach-* headers. However, they haven't been included
in the test because they aren't official architectures supported by Debian.

minor tweak: clean up the linux-headers package by using tar exclude option.

Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>